---
title: "Final Project Report"
author: "Jared Cao, Macklin Yarris, Abby Crilley"
date: "April 24th, 2020"
output: 
    html_notebook:
    fig_height: 6
    fig_width: 10
---
### Clean up environment and load packages
```{r}
# clean up the RStudio environment 
rm(list = ls())

# load all packages here: `mosaic`, `tidyverse`, `lubridate`, and all others used
library(tidyverse)
library(mosaic)
library(lubridate)
library(DataComputing)
```

## Guiding Question:

# Are suicide rates and world happiness inversely correlated?

<br>

## Data Access

```{r}
SuicideRates <-
  read.csv(file.choose())
```

```{r}
WorldHappiness2015 <-
  read.csv(file.choose())
```

```{r}
WorldHappiness2016 <-
  read.csv(file.choose())
```

```{r}
head(SuicideRates)
head(WorldHappiness2015)
head(WorldHappiness2016)
```

## Data Wrangling

<br>

# Joined World Happiness (.x is 2015 and .y is 2016)

```{r}
WorldHappiness2015 <-
  WorldHappiness2015 %>%
  mutate(year = "Happiness2015")
```

```{r}
WorldHappiness2016 <-
  WorldHappiness2016 %>%
  mutate(year = "Happiness2016")
```

```{r}
WorldHappiness <-
  WorldHappiness2015 %>%
  full_join(WorldHappiness2016)
```

```{r}
RecentSuicideRates <-
  SuicideRates %>%
  filter(year == 2015 | year == 2016)
```

```{r}
RecentSuicideRates <-
  RecentSuicideRates %>%
  select(country, year, sex, population, suicides_no, suicides.100k.pop)

RecentSuicideRates <-
  RecentSuicideRates %>%
  group_by(country, year, sex) %>%
  summarise(totalsuicides = sum(suicides_no))
RecentSuicideRates
```

```{r}
WorldHappiness <-
  WorldHappiness %>%
  select(country = Country, Happiness.Score, year)
WorldHappiness
```

```{r}
SuicideByYear <-
  RecentSuicideRates %>%
  spread(key = year, value = totalsuicides)

Suicide2015<-
  SuicideByYear[1:3]
names(Suicide2015)[3] <- "Year2015"
Suicide2015
```

```{r}
SuicideByYear <-
  SuicideByYear %>%
  na.omit()

names(SuicideByYear)[3] <- "Year2015"
names(SuicideByYear)[4] <- "Year2016"
SuicideByYear
```

```{r}
WorldHappinessByYear <-
  WorldHappiness %>%
  spread(key = year, value = Happiness.Score) %>%
  na.omit
WorldHappinessByYear

Happiness2015<-WorldHappinessByYear[1:2]
```

```{r}
SuicideHappiness <-
  SuicideByYear %>%
  inner_join(WorldHappinessByYear)
SuicideHappiness

SH2015<-
Suicide2015%>%
  inner_join(Happiness2015)
```


## Data Visualization
```{r}
SuicideHappiness%>%
  ggplot(aes(x = Happiness2015, y = Year2015, color = country)) +
  geom_point() +
  geom_point(aes(x = Happiness2016, y = Year2016, color = country, fill = country), alpha = 0.5) +
  facet_wrap(~sex) +
  xlab("Happiness Scores in 2015-16") +
  ylab("Suicides in 2015-16") +
  theme(legend.position = "bottom") +
  ylim(0, 2000)
```

```{r}
SH2015%>%
  ggplot(aes(x = Happiness2015, y = Year2015)) +
  geom_point() +
  geom_smooth() +
  ylim(0, 10000) +
  ylab("Country Suicides in 2015") +
  xlab("Country Happiness Scores in 2015")
```

